services:

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:8080"
    networks:
      - teamboard-net

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:5000"
    networks:
      - teamboard-net

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - teamboard-net
    volumes:
      - teamboard-db:/var/lib/postgresql/data

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "${PORTAINER_PORT}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - teamboard-net

networks:
  teamboard-net:
    driver: bridge

volumes:
  - /database/init.sql:/docker-entrypoint-initdb.d/init.sql
